### PR TITLE
Fix lint errors and warnings

### PR DESCRIPTION
**Pull request by dallonf**
truly, a meaningful contribution to this project

### CODE REVIEW

**Review by Willdotwhite — DISMISSED** [review]

**Comment by dallonf** [comment]
Please don't merge just yet - wanna mess with the GitHub Action a bit

**Comment by runny-yolk** [comment]
Is the aim of this PR to enable auto-fixing by ESLint? Because we have a scenario [here](https://github.com/Willdotwhite/team-finder-ui/pull/28/commits/0fd21e8c8c34ce001a4a04e933c4fefda8aa65e4) where an auto-fix would break the code.

**Comment by runny-yolk** [comment]
Plus I think it gets us into better practice to have ESLint running locally and to do fixes manually

**Comment by dallonf** [comment]
Auto-fixes will typically only make harmless changes. In regards to the unused import that breaks if removed... that's so concerning to me I'd want to investigate further rather than suppress ESLint. Anyways, the aim of this PR is just to fix all the lint errors that crept in over the last couple of days - was experimenting with auto-fixes as a bonus. I'll move that into a separate PR, I guess.

**Comment by runny-yolk** [comment]
> Auto-fixes will typically only make harmless changes. In regards to the unused import that breaks if removed... that's so concerning to me I'd want to investigate further rather than suppress ESLint. Anyways, the aim of this PR is just to fix all the lint errors that crept in over the last couple of days - was experimenting with auto-fixes as a bonus. I'll move that into a separate PR, I guess.

Turns out I was just mis-reading the code 🤦 Big L for me.

**Review by runny-yolk — APPROVED** [review]
All good!

**Pull request merged**
